# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CSLikeProfile.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x43SLikeProfile.proto\x12\x0clike_profile\"<\n\x10\x43SLikeProfileReq\x12\x11\n\ttarget_id\x18\x01 \x01(\x04\x12\x15\n\rtarget_region\x18\x02 \x01(\t\"%\n\x0e\x41\x63\x63ountIDSlice\x12\x13\n\x0b\x61\x63\x63ount_ids\x18\x01 \x03(\x04\"J\n\x13\x43SGetLikedRecordRes\x12\x33\n\rliked_profile\x18\x01 \x01(\x0b\x32\x1c.like_profile.AccountIDSliceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CSLikeProfile_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CSLIKEPROFILEREQ']._serialized_start=37
  _globals['_CSLIKEPROFILEREQ']._serialized_end=97
  _globals['_ACCOUNTIDSLICE']._serialized_start=99
  _globals['_ACCOUNTIDSLICE']._serialized_end=136
  _globals['_CSGETLIKEDRECORDRES']._serialized_start=138
  _globals['_CSGETLIKEDRECORDRES']._serialized_end=212
# @@protoc_insertion_point(module_scope)
